
package tech.pathtoprogramming.reactive;

import tech.pathtoprogramming.soapy_sinq.GetSinqRequest;
import tech.pathtoprogramming.soapy_sinq.GetSinqResponse;
import tech.pathtoprogramming.soapy_sinq.ObjectFactory;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SinqServicePort", targetNamespace = "http://pathToProgramming.tech/soapy-sinq")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SinqServicePort {


    /**
     * 
     * @param getSinqRequest
     * @return
     *     returns javax.xml.ws.Response<tech.pathtoprogramming.reactive.GetSinqResponse>
     */
    @WebMethod(operationName = "getSinq")
    public Response<tech.pathtoprogramming.soapy_sinq.GetSinqResponse> getSinqAsync(
        @WebParam(name = "getSinqRequest", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqRequest")
                tech.pathtoprogramming.soapy_sinq.GetSinqRequest getSinqRequest);

    /**
     * 
     * @param getSinqRequest
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getSinq")
    public Future<?> getSinqAsync(
        @WebParam(name = "getSinqRequest", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqRequest")
                tech.pathtoprogramming.soapy_sinq.GetSinqRequest getSinqRequest,
        @WebParam(name = "getSinqResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<tech.pathtoprogramming.soapy_sinq.GetSinqResponse> asyncHandler);

    /**
     * 
     * @param getSinqRequest
     * @return
     *     returns tech.pathtoprogramming.reactive.GetSinqResponse
     */
    @WebMethod
    @WebResult(name = "getSinqResponse", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqResponse")
    public GetSinqResponse getSinq(
        @WebParam(name = "getSinqRequest", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqRequest")
                GetSinqRequest getSinqRequest);
}
