
package tech.pathtoprogramming.soapy_sinq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SinqServicePort", targetNamespace = "http://pathToProgramming.tech/soapy-sinq")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SinqServicePort {


    /**
     * 
     * @param getSinqRequest
     * @return
     *     returns GetSinqResponse
     */
    @WebMethod
    @WebResult(name = "getSinqResponse", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqResponse")
    public GetSinqResponse getSinq(
        @WebParam(name = "getSinqRequest", targetNamespace = "http://pathToProgramming.tech/soapy-sinq", partName = "getSinqRequest")
                GetSinqRequest getSinqRequest);

}
